[package]
name = "emulator"
version = "0.1.0"
authors = ["codemyst <code@myst.rs>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.5"
